apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-xiaoming
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: xiaomingpv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-xiaoming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-xiaoming
  template:
    metadata:
      name: nginx-xiaoming
      labels:
        app: nginx-xiaoming
    spec:
      containers:
      - name: nginx-xiaoming
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: http-file
      volumes:
      - name: http-file
        persistentVolumeClaim:
          claimName: nginx-xiaoming
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-xiaoming
spec:
  selector:
    app: nginx-xiaoming
  ports:
  - port: 80
    name: nginx-xiaoming-port
    targetPort: 80
    protocol: TCP
